sudo: false

language: cpp

env:
  - KVER=3.16
  - KVER=3.17
  - KVER=3.18
  - KVER=3.19
  - KVER=4.0
  - KVER=4.1
  - KVER=4.2
  - KVER=4.3
  - KVER=4.4
  - KVER=4.5
  - KVER=master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bc
      - g++-4.8

script:
  - ./ci/build_against_kernel ${KVER}
