sudo: false

language: cpp

env:
  - KVER=3.16
  - KVER=3.17
  - KVER=3.18
  - KVER=3.19
  - KVER=4.0
  - KVER=4.1
  - KVER=4.2
  - KVER=4.3
  - KVER=4.4
  - KVER=4.5
  - KVER=latest

addons:
  apt:
    packages:
      - bc

script:
  - ./ci/build_against_kernel ${KVER}
